/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Workshop_Manager;



public class App {
    
    
    

    public static void main(String[] args) {
        mainview m = new mainview();
        m.setVisible(true);
        
        
    }
  
}
